/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface TestContractInterface extends ethers.utils.Interface {
  functions: {
    "doSomethingInt(uint256)": FunctionFragment;
    "getSomethingInt()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "doSomethingInt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSomethingInt",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "doSomethingInt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSomethingInt",
    data: BytesLike
  ): Result;

  events: {};
}

export class TestContract extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: TestContractInterface;

  functions: {
    doSomethingInt(
      _intValue: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "doSomethingInt(uint256)"(
      _intValue: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getSomethingInt(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getSomethingInt()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;
  };

  doSomethingInt(
    _intValue: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "doSomethingInt(uint256)"(
    _intValue: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getSomethingInt(overrides?: CallOverrides): Promise<BigNumber>;

  "getSomethingInt()"(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    doSomethingInt(
      _intValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "doSomethingInt(uint256)"(
      _intValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getSomethingInt(overrides?: CallOverrides): Promise<BigNumber>;

    "getSomethingInt()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    doSomethingInt(
      _intValue: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "doSomethingInt(uint256)"(
      _intValue: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getSomethingInt(overrides?: CallOverrides): Promise<BigNumber>;

    "getSomethingInt()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    doSomethingInt(
      _intValue: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "doSomethingInt(uint256)"(
      _intValue: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getSomethingInt(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getSomethingInt()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
