/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import { Ierc721Receiver } from "./Ierc721Receiver";

export class Ierc721ReceiverFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Ierc721Receiver {
    return new Contract(address, _abi, signerOrProvider) as Ierc721Receiver;
  }
}

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "operator",
        type: "address"
      },
      {
        name: "from",
        type: "address"
      },
      {
        name: "tokenId",
        type: "uint256"
      },
      {
        name: "data",
        type: "bytes"
      }
    ],
    name: "onERC721Received",
    outputs: [
      {
        name: "",
        type: "bytes4"
      }
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  }
];
