/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */
export * from "./DealRoomFactory";
export * from "./DealRoomDeployerFactory";
export * from "./Erc20Factory";
export * from "./Erc20BurnableFactory";
export * from "./Erc20CappedFactory";
export * from "./Erc20DetailedFactory";
export * from "./Erc20MintableFactory";
export * from "./Erc20PausableFactory";
export * from "./Erc721Factory";
export * from "./Erc721BurnableFactory";
export * from "./Erc721DetailedFactory";
export * from "./Erc721EnumerableFactory";
export * from "./Erc721FullFactory";
export * from "./Erc721HolderFactory";
export * from "./Erc721MetadataFactory";
export * from "./Erc721MintableFactory";
export * from "./Erc721PausableFactory";
export * from "./MigrationsFactory";
export * from "./WhitelistedRoleFactory";
